services:
#  OUR POSTGRESQL DATABASE
  db:
#    THE DOCKER IMAGE OF POSTGRES -- WE CAN SPECIFY THE VERSION, BUT WE'LL USE THE LATEST
    image: postgres:latest
#    THE PORTS TO EXPOSE -- THE FIRST ONE IS THE PORT ON OUR LOCAL MACHINE, AND THE SECOND ONE IS THE PORT INSIDE THE CONTAINER
    ports:
      - "1126:5432"
# THE RESTART POLICY -- THIS WILL RESTART THE CONTAINER IF IT CRASHES
    restart: always
#    THE POSTGRESQL ENVIRONMENT VARIABLES -- THESE ARE USED TO SET UP THE DATABASE WHEN THE CONTAINER IS FIRST CREATED
    environment:

      POSTGRES_USER: create
      POSTGRES_PASSWORD: password
#      DATABASE NAME HERE
      POSTGRES_DB: task_tracker_db