spring.application.name=task_tracker
#POSTGRESQL PROPERTIES
spring.datasource.driver-class-name=org.postgresql.Driver
#Docker Db Name with port
spring.datasource.url=jdbc:postgresql://localhost:1126/task_tracker_db
spring.datasource.username=create
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update