spring.application.name=task_tracker
#POSTGRESQL PROPERTIES
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:1126/postgres
spring.datasource.username=create
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update